use std::path::Path;

use qualitycheck::walker::{is_generated, is_source_file};

#[test]
fn test_source_files_are_recognized_by_extension() {
    for source in [
        "src/main.rs", "app/Controller.java", "web/Form.tsx", "lib/util.py", "cmd/serve.go",
        "Sources/App.swift", "scripts/deploy.sh", "db/migrate.sql", "src/Model.KT",
    ] {
        assert!(is_source_file(Path::new(source)), "{source} should be source");
    }
    for other in [
        "README.md", ".gitignore", "Cargo.toml", "package.json", "package-lock.json",
        ".github/workflows/ci.yml", "LICENSE", "assets/logo.svg", "docs/guide.txt",
    ] {
        assert!(!is_source_file(Path::new(other)), "{other} should not be source");
    }
}

#[test]
fn test_vendored_minified_and_generated_names_are_not_source() {
    for skipped in [
        "vendor/github.com/pkg/errors/errors.go", "web/node_modules/react/index.js",
        "third_party/zlib/inflate.c", "dist/app.js", "static/app.min.js", "api/service.pb.go",
        "proto/service_pb2.py", "lib/model.g.dart", "Forms/Main.designer.cs",
        "src/schema.generated.ts", "src/types_generated.rs",
    ] {
        assert!(!is_source_file(Path::new(skipped)), "{skipped} should be skipped");
    }
    // A directory merely containing a vendored name as part of a word is fine.
    assert!(is_source_file(Path::new("src/vendors/client.rs")));
}

#[test]
fn test_generated_markers_count_only_in_leading_comments() {
    assert!(is_generated(b"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n"));
    assert!(is_generated(b"/*\n * @generated\n */\nexport const x = 1;\n"));
    assert!(is_generated(b"# This file was automatically generated by alembic.\nimport os\n"));
    assert!(is_generated(b"// <auto-generated>\nnamespace App {}\n"));

    // Hand-written code that merely mentions a marker in a string is not generated.
    assert!(!is_generated(b"const MARKER: &str = \"@generated\";\nfn main() {}\n"));
    // Nor is a marker far below the file header.
    let late = format!("{}// @generated\n", "fn f() {}\n".repeat(25));
    assert!(!is_generated(late.as_bytes()));
    assert!(!is_generated(b"// Service for generated reports.\nfn main() {}\n"));
}
